import { ActuatorCard, ActuatorPlanDuration } from '../types';

export const ACTUATOR_PLANS: Record<ActuatorPlanDuration, { days: ActuatorPlanDuration; priceUsd: number; label: string; periodText: string; savingsText?: string }> = {
  30: {
    days: 30,
    priceUsd: 1.70,
    label: '30 Days (1 Month)',
    periodText: '30 Days Node Access',
  },
  180: {
    days: 180,
    priceUsd: 10.20,
    label: '180 Days (6 Months)',
    periodText: '6 Months Node Access',
    savingsText: 'Popular (6 Months)',
  },
  360: {
    days: 360,
    priceUsd: 20.40,
    label: '360 Days (1 Year)',
    periodText: '1 Full Year (360 Days)',
    savingsText: 'Best Value (1 Year)',
  },
};

/**
 * Format any raw digits into standard 16-digit space-separated format:
 * "4532890123456789" -> "4532 8901 2345 6789"
 */
export function format16DigitCard(raw: string): string {
  const digits = raw.replace(/\D/g, '').slice(0, 16);
  const parts: string[] = [];
  for (let i = 0; i < digits.length; i += 4) {
    parts.push(digits.slice(i, i + 4));
  }
  return parts.join(' ');
}

/**
 * Clean card input down to 16 raw digits
 */
export function cleanCardDigits(input: string): string {
  return input.replace(/\D/g, '').slice(0, 16);
}

/**
 * Generate a cryptographically clean 16-digit Actuator Card
 */
export function generateActuatorCard(params: {
  days: ActuatorPlanDuration;
  assignedToUserId?: string;
  assignedToName?: string;
  memo?: string;
}): ActuatorCard {
  const prefixes = ['4532', '5241', '8492', '4128', '5590'];
  const prefix = prefixes[Math.floor(Math.random() * prefixes.length)];
  
  // 12 random digits
  let rest = '';
  for (let i = 0; i < 12; i++) {
    rest += Math.floor(Math.random() * 10).toString();
  }
  const cardNumber = `${prefix}${rest}`;
  const plan = ACTUATOR_PLANS[params.days];

  return {
    id: `card_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
    cardNumber,
    formattedCardNumber: format16DigitCard(cardNumber),
    days: params.days,
    priceUsd: plan.priceUsd,
    label: plan.label,
    createdAt: new Date().toISOString(),
    status: 'active',
    assignedToUserId: params.assignedToUserId,
    assignedToName: params.assignedToName,
    memo: params.memo || 'Generated by Admin Treasury',
  };
}

/**
 * Initial seeded demo cards for testing
 */
export const INITIAL_ACTUATOR_CARDS: ActuatorCard[] = [
  {
    id: 'card_demo_30d',
    cardNumber: '4532890123456789',
    formattedCardNumber: '4532 8901 2345 6789',
    days: 30,
    priceUsd: 1.70,
    label: '30 Days (1 Month)',
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    status: 'active',
    memo: 'Admin Treasury Batch #01 (30 Days)',
  },
  {
    id: 'card_demo_180d',
    cardNumber: '5241789012345678',
    formattedCardNumber: '5241 7890 1234 5678',
    days: 180,
    priceUsd: 10.20,
    label: '180 Days (6 Months)',
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    status: 'active',
    memo: 'Admin Treasury Batch #02 (180 Days / 6 Mo)',
  },
  {
    id: 'card_demo_360d',
    cardNumber: '8492345678901234',
    formattedCardNumber: '8492 3456 7890 1234',
    days: 360,
    priceUsd: 20.40,
    label: '360 Days (1 Year)',
    createdAt: new Date(Date.now() - 3600000 * 72).toISOString(),
    status: 'active',
    memo: 'Admin Treasury VIP Grant (360 Days / 1 Yr)',
  },
  {
    id: 'card_demo_used_01',
    cardNumber: '4128901245678901',
    formattedCardNumber: '4128 9012 4567 8901',
    days: 30,
    priceUsd: 1.70,
    label: '30 Days (1 Month)',
    createdAt: new Date(Date.now() - 3600000 * 120).toISOString(),
    status: 'redeemed',
    redeemedByUserId: 'mem_01',
    redeemedByName: 'Elena Rostova',
    redeemedAt: new Date(Date.now() - 3600000 * 96).toISOString(),
    memo: 'Redeemed by node @elena_r',
  },
];
